### ISSUE TITLE
link not found

### ISSUE THREAD

**Issue by YihanJessieLi** [bulik/ldsc#51] opened 2016-05-16 15:39 UTC
Hi, 

The link to the pre-computed LD score page no longer works. Is this temporary or permanent? 
https://data.broadinstitute.org/alkesgroup/LDSCORE/

Best,
Jessie

**Comment by hilaryfinucane** [comment] 2016-05-16 22:25
Hi Jessie,

I think there was some temporary disruption, since the link seems to be
working now. Let me know if you have further issues.

Hilary

**Comment by YihanJessieLi** [comment] 2016-05-18 08:53
Thank you very much. Best, Jessie

**Comment by YihanJessieLi** [comment] 2016-05-18 11:08
So there are two baseline files (baseline_ldscores_old.tgz, baseline_ldscores_1000G_Phase3.tgz), I tried the latest 1000G_Phase3 version on a munged summary statistics file, it gives the following error msg (Error parsing .annot file.).  
Q1: what's difference between the two baseline LD scores? 
Q2: what might be the cause of the error msg? 

*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.0
* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call: 
./ldsc.py \
--h2 /data/scratch/project/pharma/LDSC/SGE_output_all_rmHeader_munge/GWAS104.sumstats.gz \
--ref-ld-chr /data/scratch/project/pharma/LDSC/baseline/baseline. \
--out /data/scratch/project/pharma/LDSC/GWAS104_baseline \
--overlap-annot  \
--frqfile-chr /data/scratch/project/pharma/LDSC/1000G_frq/1000G.mac5eur. \
--w-ld-chr /data/scratch/project/pharma/LDSC/weights_hm3_no_hla/weights. 

Beginning analysis at Wed May 18 08:45:45 2016
Reading summary statistics from /data/scratch/project/pharma/LDSC/SGE_output_all_rmHeader_munge/GWAS104.sumstats.gz ...
Read summary statistics for 1069082 SNPs.
Reading reference panel LD Score from /data/scratch/project/pharma/LDSC/baseline/baseline.[1-22] ...
Read reference panel LD Scores for 1190321 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from /data/scratch/project/pharma/LDSC/weights_hm3_no_hla/weights.[1-22] ...
Read regression weight LD Scores for 1242190 SNPs.
After merging with reference panel LD, 1064713 SNPs remain.
After merging with regression SNP LD, 967490 SNPs remain.
Removed 1 SNPs with chi^2 > 80 (967489 SNPs remain)
Total Observed scale h2: 0.0681 (0.0088)
Categories: baseL2_0 Coding_UCSC.bedL2_0 Coding_UCSC.extend.500.bedL2_0 Conserved_LindbladToh.bedL2_0 Conserved_LindbladToh.extend.500.bedL2_0 CTCF_Hoffman.bedL2_0 CTCF_Hoffman.extend.500.bedL2_0 DGF_ENCODE.bedL2_0 DGF_ENCODE.extend.500.bedL2_0 DHS_peaks_Trynka.bedL2_0 DHS_Trynka.bedL2_0 DHS_Trynka.extend.500.bedL2_0 Enhancer_Andersson.bedL2_0 Enhancer_Andersson.extend.500.bedL2_0 Enhancer_Hoffman.bedL2_0 Enhancer_Hoffman.extend.500.bedL2_0 FetalDHS_Trynka.bedL2_0 FetalDHS_Trynka.extend.500.bedL2_0 H3K27ac_Hnisz.bedL2_0 H3K27ac_Hnisz.extend.500.bedL2_0 H3K27ac_PGC2.bedL2_0 H3K27ac_PGC2.extend.500.bedL2_0 H3K4me1_peaks_Trynka.bedL2_0 H3K4me1_Trynka.bedL2_0 H3K4me1_Trynka.extend.500.bedL2_0 H3K4me3_peaks_Trynka.bedL2_0 H3K4me3_Trynka.bedL2_0 H3K4me3_Trynka.extend.500.bedL2_0 H3K9ac_peaks_Trynka.bedL2_0 H3K9ac_Trynka.bedL2_0 H3K9ac_Trynka.extend.500.bedL2_0 Intron_UCSC.bedL2_0 Intron_UCSC.extend.500.bedL2_0 PromoterFlanking_Hoffman.bedL2_0 PromoterFlanking_Hoffman.extend.500.bedL2_0 Promoter_UCSC.bedL2_0 Promoter_UCSC.extend.500.bedL2_0 Repressed_Hoffman.bedL2_0 Repressed_Hoffman.extend.500.bedL2_0 SuperEnhancer_Hnisz.bedL2_0 SuperEnhancer_Hnisz.extend.500.bedL2_0 TFBS_ENCODE.bedL2_0 TFBS_ENCODE.extend.500.bedL2_0 Transcribed_Hoffman.bedL2_0 Transcribed_Hoffman.extend.500.bedL2_0 TSS_Hoffman.bedL2_0 TSS_Hoffman.extend.500.bedL2_0 UTR_3_UCSC.bedL2_0 UTR_3_UCSC.extend.500.bedL2_0 UTR_5_UCSC.bedL2_0 UTR_5_UCSC.extend.500.bedL2_0 WeakEnhancer_Hoffman.bedL2_0 WeakEnhancer_Hoffman.extend.500.bedL2_0
Lambda GC: 1.0741
Mean Chi^2: 1.1029
Intercept: 1.005 (0.0077)
Ratio: 0.0484 (0.0753)
Reading annot matrix from /data/scratch/project/pharma/LDSC/baseline/baseline.[1-22] ...
/data/home/jessieli/github/ldsc/ldscore/parse.py:121: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_annot = df_annot[(.95 > df_frq.FRQ) & (df_frq.FRQ > 0.05)]
Error parsing .annot file.
Traceback (most recent call last):
  File "/home/jessieli/github/ldsc/ldsc.py", line 628, in <module>
    sumstats.estimate_h2(args, log)
  File "/data/home/jessieli/github/ldsc/ldscore/sumstats.py", line 302, in estimate_h2
    overlap_matrix, M_tot = _read_annot(args, log)
  File "/data/home/jessieli/github/ldsc/ldscore/sumstats.py", line 95, in _read_annot
    'annot matrix', ps.annot, frqfile=args.frqfile_chr)
  File "/data/home/jessieli/github/ldsc/ldscore/sumstats.py", line 151, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/data/home/jessieli/github/ldsc/ldscore/parse.py", line 198, in annot
    for i, fh in enumerate(fh_list)]
  File "/data/home/jessieli/github/ldsc/ldscore/parse.py", line 121, in annot_parser
    df_annot = df_annot[(.95 > df_frq.FRQ) & (df_frq.FRQ > 0.05)]
  File "/data/home/jessieli/github/ldsc/env/local/lib/python2.7/site-packages/pandas/core/frame.py", line 1986, in __getitem__
    return self._getitem_array(key)
  File "/data/home/jessieli/github/ldsc/env/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2026, in _getitem_array
    key = check_bool_indexer(self.index, key)
  File "/data/home/jessieli/github/ldsc/env/local/lib/python2.7/site-packages/pandas/core/indexing.py", line 1755, in check_bool_indexer
    raise IndexingError('Unalignable boolean Series key provided')
IndexingError: Unalignable boolean Series key provided

Analysis finished at Wed May 18 08:47:17 2016
Total time elapsed: 1.0m:32.49s
Traceback (most recent call last):
  File "/home/jessieli/github/ldsc/ldsc.py", line 628, in <module>
    sumstats.estimate_h2(args, log)
  File "/data/home/jessieli/github/ldsc/ldscore/sumstats.py", line 302, in estimate_h2
    overlap_matrix, M_tot = _read_annot(args, log)
  File "/data/home/jessieli/github/ldsc/ldscore/sumstats.py", line 95, in _read_annot
    'annot matrix', ps.annot, frqfile=args.frqfile_chr)
  File "/data/home/jessieli/github/ldsc/ldscore/sumstats.py", line 151, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/data/home/jessieli/github/ldsc/ldscore/parse.py", line 198, in annot
    for i, fh in enumerate(fh_list)]
  File "/data/home/jessieli/github/ldsc/ldscore/parse.py", line 121, in annot_parser
    df_annot = df_annot[(.95 > df_frq.FRQ) & (df_frq.FRQ > 0.05)]
  File "/data/home/jessieli/github/ldsc/env/local/lib/python2.7/site-packages/pandas/core/frame.py", line 1986, in __getitem__
    return self._getitem_array(key)
  File "/data/home/jessieli/github/ldsc/env/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2026, in _getitem_array
    key = check_bool_indexer(self.index, key)
  File "/data/home/jessieli/github/ldsc/env/local/lib/python2.7/site-packages/pandas/core/indexing.py", line 1755, in check_bool_indexer
    raise IndexingError('Unalignable boolean Series key provided')
pandas.core.indexing.IndexingError: Unalignable boolean Series key provided

**Comment by YihanJessieLi** [comment] 2016-05-18 16:16
I think I figured out the reason for the job failure which is to do with memory. So a default 3.5G RAM on our cluster is the reason for the job failure. Could you let me know what the memory usage requirement is for the stratified LD score regression calculation?

**Comment by hilaryfinucane** [comment] 2016-05-25 00:03
Hi Jessie,

Thanks for your email. The problem isn't memory, it's that you are using
1000G Phase1 frq files with 1000G Phase 3 LD scores. I've uploaded the
1000G Phase 3 frq files so you can use these instead.

Best,

Hilary

**Comment by YihanJessieLi** [comment] 2016-05-26 13:41
Thank you very much. Jessie

**Comment by rkwalters** [comment] 2016-08-01 19:41
Hi Jessie,
I'm closing this issue since it appears to be resolved. Feel free to email the ldsc user group (https://groups.google.com/forum/#!forum/ldsc_users) if you have any further questions.
Thanks,
Raymond

**Closed by rkwalters** 2016-08-01 19:41 UTC
