### ISSUE TITLE
munge_sumstats.py error

### ISSUE THREAD

**Issue by dbackenroth** [bulik/ldsc#47] opened 2016-03-16 00:16 UTC
Hi-
Thanks for making this great software available.  I'm running into an error when using munge_sumstats.py.  

**Here's the error message**

Call: 
./munge_sumstats.py \
--out IGANTMP \
--merge-alleles /ifs/scratch/msph/db2175/data/LDSC/PartitionedHeritability/LDSCORE/w_hm3.snplist \
--a1-inc  \
--N 11946.0 \
--snp rsID \
--sumstats META_ALL5COHORTS_IGAN_08RSQ.txt 

Interpreting column names as follows:
Allele2:    Allele 2, interpreted as non-ref allele for signed sumstat.
MarkerName: Variant ID (e.g., rs number)
rsID:   Variant ID (e.g., rs number)
Allele1:    Allele 1, interpreted as ref allele for signed sumstat.
P-value:    p-Value

Reading list of SNPs for allele merge from /ifs/scratch/msph/db2175/data/LDSC/PartitionedHeritability/LDSCORE/w_hm3.snplist
Read 1217311 SNPs for allele merge.
Reading sumstats from META_ALL5COHORTS_IGAN_08RSQ.txt into memory 5000000.0 SNPs at a time.
.
ERROR converting summary statistics:

Traceback (most recent call last):
  File "/ifs/scratch/msph/biostat/db2175/ldsc/ldsc/munge_sumstats.py", line 639, in munge_sumstats
    dat = parse_dat(dat_gen, cname_translation, merge_alleles, log, args)
  File "/ifs/scratch/msph/biostat/db2175/ldsc/ldsc/munge_sumstats.py", line 250, in parse_dat
    if ii.sum() == 0:
  File "/ifs/scratch/msph/biostat/db2175/ldsc/lib/python2.7/site-packages/pandas/core/generic.py", line 698, in **nonzero**
    .format(self.**class**.**name**))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Conversion finished at Tue Mar 15 20:09:26 2016

**This is my script:**
# !/bin/bash

wd=`pwd`
out=IGANTMP
f=META_ALL5COHORTS_IGAN_08RSQ.txt
N=11946
hapmap=/ifs/scratch/msph/db2175/data/LDSC/PartitionedHeritability/LDSCORE/
w_hm3.snplist
cd /ifs/scratch/msph/biostat/db2175/ldsc
source bin/activate
cd $wd

python /ifs/scratch/msph/biostat/db2175/ldsc/ldsc/munge_sumstats.py --su
mstats $f\
       --merge-alleles $hapmap\
       --out $out --a1-inc --N $N --snp rsID

**I have the right version of pandas (and of the other packages as well):**

Python 2.7.6 (default, Dec 10 2013, 14:55:31) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import pandas as pd
> > > pd.**version**
> > > '0.15.2'

Thanks for your help!
Daniel

**Comment by rkwalters** [comment] 2016-03-16 16:08
Hi Daniel,
From you log file, it looks like the problem is that you have two columns (rsID and `MarkerName) both getting interpreted as the SNP names. Assuming from your command line that "rsID" is the one you want to use, adding `--ignore MarkerName` should fix this issue.
Cheers,
Raymond

P.S. @tpoterba: This isn’t the first time this issue has popped up, so a direct check on this to at least provide more informative error messages might be in order? Probably somewhere around lines 570-600 of `munge_sumstats.py`, where there are already checks that required columns are present and that there’s only 1 column of sumstats.

**Comment by dbackenroth** [comment] 2016-03-17 13:37
Thanks, that worked.

**Comment by rkwalters** [comment] 2017-04-22 01:26
Hi all,
I'm closing this issue thread since it appears this specific error was resolved and a more general fix was made (in the form of a more informative error message, see github pull #75). 

If there are still problems with this munging error or any other issues feel free to follow up here or via [the google group](https://groups.google.com/forum/#!forum/ldsc_users).

Cheers,
Raymond

**Closed by rkwalters** 2017-04-22 01:26 UTC
