### ISSUE TITLE
Question regarding LD Score Estimation

### ISSUE THREAD

**Issue by amitsud** [bulik/ldsc#50] opened 2016-04-13 16:53 UTC
Hi,

I am using the LD Score Regression method to compute the genetic correlation between two different phenotypes in patients from European ancestry (using summary statistic data).  I have noticed some of my SNPs which demonstrate genome-wide significance in both phenotypes are not present 'w_hm3.snplist' file or the 'eur_w_ld_chr' folder with the precomputed ld scores.   Do the authors think this will make a difference to the estimate?  If so, would it be wise to compute additional LD scores from the reference panel from which I imputed the data?  Furthermore, if I do this, do I need to update the snplist file used to munge/reformat the data prior to analysis?  If so, could the authors please help suggest the best way to do this (including filtering)?  Many thanks.

BW

Amit

**Comment by rkwalters** [comment] 2016-04-13 21:29
Hi Amit,
We’re generally not too concerned with this phenomenon. For example, if you follow the heritability tutorial you can check the example files and find that the schizophrenia results have 18 genome-wide significant SNPs but only 11 of them pass the merge with w_hm3.snplist. The expectation is that as long as you have a sufficiently polygenic trait (as is the model for LD score regression) then the HapMap3 SNPs should be representative of the overall polygenic signal even if some specific SNPs that have reached significance are not on that list.

If you want to compute your own LD scores to verify this then you would indeed need to update the list used for munging. You’ll also want to be sure that you use an unbiased genome-wide selection of SNPs for computing the new LD scores, rather than just manually adding your significant SNPs to the current selection.

The published LD score papers have a lot of extended discussion of how best to filter SNPs. Note that there are separate considerations to define filters for regression SNPs (present in the merge-alleles and ld-chr files; e.g. info > .9, maf > 5%, etc) and reference SNPs (used to compute the ld-chr files; e.g. minor allele count > 5, etc).  

Cheers,
Raymond

**Comment by amitsud** [comment] 2016-04-14 11:02
Hi Raymond,

Thank you for your quick and helpful reply. I may try and calculate LD scores for a different population but understand your explanation and realise it will not make a large difference to the estimate.

Reading your methods I understand when you calculated LD scores you excluded centromeres including a 3Mb region and you also excluded long-range LD regions.  May I ask, how did you calculate the latter (or is there a place where I can access this data)?

BW

Amit

**Comment by rkwalters** [comment] 2016-04-14 16:17
Hi Amit,
Those regions of long-range LD come from the cited paper by Price et al. (full text: PMC2443852). See Table 1 and it’s legend for the full list of 24 long-range LD regions identified in Europeans.
Cheers,
Raymond

**Comment by rkwalters** [comment] 2016-05-24 16:22
Closing this thread as answered since there's been no additional activity in the past month. Follow up questions are always welcome in the ldsc users group: [https://groups.google.com/forum/#!forum/ldsc_users](https://groups.google.com/forum/#!forum/ldsc_users)

Cheers,
Raymond

**Closed by rkwalters** 2016-05-24 16:22 UTC
